trigger:
  - master

jobs:
  - template: .azure-pipelines/lint-job.yml

  - template: .azure-pipelines/test-job.yml
    parameters:
      name: test_on_linux_node12_eslint5
      displayName: Test on Node 12, ESLint 5, Linux
      vmImage: Ubuntu-16.04
      nodeVersion: 12.x

  - template: .azure-pipelines/test-job.yml
    parameters:
      name: test_on_linux_node10_eslint5
      displayName: Test on Node 10, ESLint 5, Linux
      vmImage: Ubuntu-16.04
      nodeVersion: 10.x

  - template: .azure-pipelines/test-job.yml
    parameters:
      name: test_on_linux_node8_eslint5
      displayName: Test on Node 8, ESLint 5, Linux
      vmImage: Ubuntu-16.04
      nodeVersion: 8.x

  - template: .azure-pipelines/test-job.yml
    parameters:
      name: test_on_linux_node6_eslint5
      displayName: Test on Node 6, ESLint 5, Linux
      vmImage: Ubuntu-16.04
      nodeVersion: 6.x

  - template: .azure-pipelines/test-job.yml
    parameters:
      name: test_on_linux_node12_eslint6rc
      displayName: Test on Node 12, ESLint 6 RC, Linux
      vmImage: Ubuntu-16.04
      nodeVersion: 12.x
      eslintVersion: ^6.0.0-rc.0

  - template: .azure-pipelines/test-job.yml
    parameters:
      name: test_on_windows_node12_eslint5
      displayName: Test on Node 12, ESLint 5, Windows
      vmImage: Windows-2019
      nodeVersion: 12.x

  - template: .azure-pipelines/test-job.yml
    parameters:
      name: test_on_macos_node12_eslint5
      displayName: Test on Node 12, ESLint 5, macOS
      vmImage: macOS-10.14
      nodeVersion: 12.x
